### ISSUE TITLE
Добавить в конфиг debug если уже не добавлено

### ISSUE THREAD

**Issue by Noob-A** [ZaWaTeam/web-cms-project#16]

**Comment by Noob-A** [comment]
Type = Boolean

**Comment by Noob-A** [comment]
Debug в фласке включиться и различные выводы

**Comment by Zahgrom34** [comment]
Принято

**Comment by Noob-A** [comment]
https://github.com/ZaWaTeam/web-cms-project/commit/e9f22ea20a513fb87dc389d88d2b43b9efdbd6c2
