### ISSUE TITLE
При неудаче подключения к MySQL, использовать SQLite

### ISSUE THREAD

**Issue by Noob-A** [ZaWaTeam/web-cms-project#19]

**Comment by Zahgrom34** [comment]
Исправлено

**Comment by Noob-A** [comment]
Не вижу где

**Comment by Zahgrom34** [comment]
> Не вижу где

Вот теперь то исправлено

**Comment by Noob-A** [comment]
мне кажеться ты не понял, суть в том что если код не может подключиться к mysql, он поменяет в конфиге на sqlite и дефолтное название базы данных. Если не доступна mysql, меняем конфиг, и сразу используем sqlite
