### ISSUE TITLE
Веб-админка

### ISSUE THREAD

**Issue by Noob-A** [ZaWaTeam/web-cms-project#24]
Создание нового каталога в **Ядре** проекта. 

- [ ] Создание необходимых моделей для работы с панелью
- [x] Создание нового Flask Blueprints для работы с request панели
- [x] Разработка User Manager Permissions. Для доступа к тем или иным вещам в панели

**Comment by Zahgrom34** [comment]
Разработка интерфейса.

**Comment by Zahgrom34** [comment]
Создание нового каталога в **Ядре** проекта. 

- Создание необходимых моделей для работы с панелью - **_частично выполнено_**
- Создание нового Flask Blueprints для работы с request панели - **_Выполнено_**
- Разработка User Manager Permissions. Для доступа к тем или иным вещам в панели - **_Надо сделать_**
